services:
  - type: web
    name: showsewa-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: showsewa-db
          property: connectionString
      - key: DIRECT_URL
        fromDatabase:
          name: showsewa-db
          property: directConnectionString
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: ESEWA_SECRET
        sync: false
      - key: KHALTI_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false

databases:
  - name: showsewa-db
    databaseName: showsewa
    plan: free

